# Generated by Django 5.2.9 on 2025-12-28 21:27

import django.db.models.deletion
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('doc_type', models.CharField(choices=[('manual', 'User Manual'), ('api', 'API Reference')], default='api', help_text='Type of documentation this section belongs to', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in sidebar')),
                ('icon', models.CharField(blank=True, help_text='Material Symbol icon name', max_length=50)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', tinymce.models.HTMLField(help_text='Rich HTML content for the article')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='documentation.documentationsection')),
            ],
            options={
                'ordering': ['section', 'order', 'title'],
            },
        ),
    ]
