package models

import "gorm.io/gorm"

// MigrateTenantModels runs AutoMigrate for all models that belong in the tenant schema.
func MigrateTenantModels(db *gorm.DB) error {
	// Drop legacy foreign keys and NOT NULL constraints so schema-per-tenant isolation works cleanly
	_ = db.Exec(`ALTER TABLE stock_movements DROP CONSTRAINT IF EXISTS fk_stock_movements_tenant;`).Error
	_ = db.Exec(`ALTER TABLE stock_movements ALTER COLUMN tenant_id DROP NOT NULL;`).Error
	_ = db.Exec(`ALTER TABLE loyalty_transactions DROP CONSTRAINT IF EXISTS fk_loyalty_transactions_tenant;`).Error
	_ = db.Exec(`ALTER TABLE loyalty_transactions ALTER COLUMN tenant_id DROP NOT NULL;`).Error

	return db.AutoMigrate(
		&Branch{},
		&Device{},
		&CashDrawerSession{},
		&Shift{},
		&StaffShift{},
		&PrintJob{},
		&Category{},
		&Product{},
		&ProductVariant{},
		&ProductComponent{},
		&ProductHistory{},
		&StockTransfer{},
		&StockTransferItem{},
		&PurchaseOrder{},
		&PurchaseOrderItem{},
		&StocktakeSession{},
		&StockMovement{},
		&Order{},
		&OrderItem{},
		&CustomerTier{},
		&Customer{},
		&LoyaltyTransaction{},
		&GiftCard{},
		&Supplier{},
		&AuditLog{},
		&SupplierProfile{},
		&SupplierProduct{},
		&SupplierLedgerEntry{},
		&ExpenseCategory{},
		&Expense{},
		&CustomerSegment{},
		&AbandonedCart{},
		&StockBatch{},
		&PaymentMethod{},
		&Payment{},
		&TaxConfiguration{},
		&Return{},
		&ReturnItem{},
		&CRMSettings{},
		&MarketingCampaign{},
		&Promotion{},
		&DiscountCode{},
		&CustomerFeedback{},
		&DiningTable{},
		&KDSTicket{},
		&SplitBillGroup{},
		&PayrollPeriod{},
		&StorefrontSettings{},
		&ProductReview{},
		&Wishlist{},
		&Coupon{},
		&NewsletterSubscription{},
		&ProductImageGallery{},
		&TenantIntegration{},
		&PayrollRecord{},
		&LeaveRequest{},
		&Attendance{},
		&ServiceCategory{},
		&Service{},
		&Appointment{},
		&ServiceCommissionRule{},
		&ServiceCommissionRecord{},
		&Quotation{},
		&QuotationItem{},
		&APIRequestLog{},
		&HoneypotAttempt{},
		&APIKey{},
		&ExternalSystem{},
		&WebhookEndpoint{},
		&WebhookEvent{},
		&Notification{},
		&StocktakeEntry{},
		&NotificationSetting{},
		&DeliveryDriver{},
		&DeliveryOrder{},
		&LedgerAccount{},
		&JournalEntry{},
		&LedgerLine{},
		&StockAlert{},
		&SupportTicket{},
		&TicketMessage{},
		&CreditAccount{},
		&CreditTransaction{},
		&BNPLInstalment{},
		&ReportSchedule{},
		&DeviceToken{},
		&SMSSenderID{},
		&SMSWallet{},
		&SMSTransaction{},
	)
}

// MigratePublicModels runs AutoMigrate for all models that belong in the public schema.
func MigratePublicModels(db *gorm.DB) error {
	return db.AutoMigrate(
		&Tenant{},
		&Domain{},
		&User{},
		&UserProfile{},
		&Plan{},
		&PricingPlan{},
		&PlanFeature{},
		&AdminRole{},
		&AdminUser{},
		&IPAllowlist{},
		&MasterAPIKey{},
		&Permission{},
		&Role{},
		&TelemetryLog{},
		&AuditLog{},
		&Subscription{},
		&BillingPayment{},
		&PromoCode{},
		&ReferralReward{},
		&BillingSettings{},
		&CrossTenantAuditLog{},
		&LegalDocument{},
		&BlogPost{},
		&DatabaseBackup{},
		&TenantMetrics{},
		&FeatureFlag{},
		&SEOSettings{},
		&Broadcast{},
		&DeviceToken{},
		&SMSGatewayConfig{},
	)
}
